version: '3'

services:
  db:
    container_name: manga-dashboard-db
    image: postgres:16-alpine
    volumes:
      - ./data/manga-dashboard-db-vol:/var/lib/postgresql/data:ro
    environment:
      - PGID=1000
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped
