version: "3"

services:
  mantium-db:
    container_name: mantium-db
    image: postgres:16-alpine
    volumes:
      - ./data/postgres-vol:/var/lib/postgresql/data
    environment:
      - PGID=1000
    ports:
      - 5432:5432
    restart: unless-stopped

  mantium-api:
    container_name: mantium-api
    image: ghcr.io/diogovalentte/mantium-api:latest
    volumes:
      - ./configs:/app/api/configs
    depends_on:
      - mangas-dashboard-db
    restart: unless-stopped

  mantium-dashboard:
    container_name: mantium-dashboard
    image: ghcr.io/diogovalentte/mantium-dashboard:latest
    ports:
      - 8501:8501
    depends_on:
      - mangas-dashboard-api
      - mangas-dashboard-db
    restart: unless-stopped
