version: '3'

services:
  mangas-dashboard-db:
    container_name: mangas-dashboard-db
    image: postgres:16-alpine
    volumes:
      - ./data/postgres-vol:/var/lib/postgresql/data:rwx
    environment:
      - PGID=1000
    env_file:
      - .env.prod
    restart: unless-stopped

  mangas-dashboard-api:
    container_name: mangas-dashboard-api
    build:
      context: .
      dockerfile: Dockerfile_API
    env_file:
      - .env.prod
    depends_on:
      - mangas-dashboard-db
    restart: unless-stopped

  mangas-dashboard:
    container_name: mangas-dashboard
    build:
      context: .
      dockerfile: Dockerfile_dashboard
    env_file:
      - .env.prod
    ports:
      - 8501:8501
    depends_on:
      - mangas-dashboard-api
      - mangas-dashboard-db
    restart: unless-stopped
