version: '3'

services:
  mantium-db:
    container_name: mantium-db
    image: postgres:16-alpine
    volumes:
      - ./data/postgres-vol:/var/lib/postgresql/data:rwx
    environment:
      - PGID=1000
    env_file:
      - .env.test
    ports:
      - 5432:5432
    restart: unless-stopped

  mantium-api:
    container_name: mantium-api
    build:
      context: .
      dockerfile: Dockerfile_API
    env_file:
      - .env.prod
    depends_on:
      - mangas-dashboard-db
    restart: unless-stopped

  mantium-dashboard:
    container_name: mantium-dashboard
    build:
      context: .
      dockerfile: Dockerfile_dashboard
    env_file:
      - .env.prod
    ports:
      - 8501:8501
    depends_on:
      - mangas-dashboard-api
      - mangas-dashboard-db
    restart: unless-stopped
